version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: bookmarks_app
    networks:
      - bookmarks
  test-db:
    image: postgres:13
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: bookmarks_app
    networks:
      - bookmarks
networks:
  bookmarks: